from django.db import models

class Dockets(models.Model):
    "Model representing a docket."
    id = models.CharField(max_length=255, primary_key=True)
    docketType = models.CharField(max_length=255, blank=True, null=True)
    lastModifiedDate = models.DateTimeField(null=True)
    agencyId = models.CharField(max_length=100, blank=True, null=True)
    title = models.TextField(null=True)
    objectId = models.CharField(max_length=255, blank=True, null=True)
    highlightedContent = models.CharField(max_length=255, blank=True, null=True)

class Documents(models.Model):
    "Model representing a document."
    id = models.CharField(max_length=255, primary_key=True)
    documentType = models.CharField(max_length=255, blank=True, null=True)
    lastModifiedDate = models.DateTimeField(null=True)
    frDocNum = models.CharField(max_length=100, blank=True, null=True)
    withdrawn = models.BooleanField(default=False)
    agencyId = models.CharField(max_length=100, blank=True, null=True)
    commentEndDate = models.DateField(null=True, blank=True)
    postedDate = models.DateField(null=True)
    title = models.TextField(null=True)
    docket = models.ForeignKey(Dockets, on_delete=models.CASCADE)
    subtype = models.CharField(max_length=255, blank=True, null=True)
    commentStartDate = models.DateField(blank=True, null=True)
    openForComment = models.BooleanField(default=False, null=True)
    objectId = models.CharField(max_length=100, blank=True, null=True)
    fullTextXmlUrl = models.CharField(max_length=255, blank=True, null=True)
    subAgy = models.CharField(max_length=255, blank=True, null=True)
    agencyType = models.CharField(max_length=100, blank=True, null=True)
    CFR = models.CharField(max_length=100, blank=True, null=True)
    RIN = models.CharField(max_length=100, blank=True, null=True)
    title = models.TextField(null=True)
    summary = models.TextField(null=True)
    dates = models.TextField(null=True)
    furtherInformation = models.TextField(blank=True, null=True)
    supplementaryInformation = models.TextField(blank=True, null=True)

class PublicComments(models.Model):
    "Model representing a public comment."
    id = models.CharField(max_length=255, primary_key=True)
    objectId = models.CharField(max_length=255)
    commentOn = models.CharField(max_length=255, blank=True, null=True)
    document = models.ForeignKey(Documents, on_delete=models.CASCADE)
    duplicateComments = models.IntegerField(default=0)
    stateProvinceRegion = models.CharField(max_length=100, blank=True, null=True)
    subtype = models.CharField(max_length=100, blank=True, null=True)
    comment = models.TextField(null=True)
    firstName = models.CharField(max_length=255, blank=True, null=True)
    lastName = models.CharField(max_length=255, blank=True, null=True)
    address1 = models.CharField(max_length=200, blank=True, null=True)
    address2 = models.CharField(max_length=200, blank=True, null=True)
    city = models.CharField(max_length=100, blank=True, null=True)
    category = models.CharField(max_length=100, blank=True, null=True)
    country = models.CharField(max_length=100, blank=True, null=True)
    email = models.EmailField(max_length=100, blank=True, null=True)
    phone = models.CharField(max_length=50, blank=True, null=True)
    govAgency = models.CharField(max_length=100, blank=True, null=True)
    govAgencyType = models.CharField(max_length=100, blank=True, null=True)
    organization = models.CharField(max_length=255, blank=True, null=True)
    originalDocumentId = models.CharField(max_length=100, blank=True, null=True)
    modifyDate = models.DateTimeField(null=True)
    pageCount = models.IntegerField(null=True)
    postedDate = models.DateTimeField(null=True)
    receiveDate = models.DateTimeField(null=True)
    title = models.TextField(null=True)
    trackingNbr = models.CharField(max_length=255, blank=True, null=True)
    withdrawn = models.BooleanField(default=False)
    reasonWithdrawn = models.CharField(max_length=255, blank=True, null=True)
    zip = models.CharField(max_length=50, blank=True, null=True)
    restrictReason = models.CharField(max_length=100, blank=True, null=True)
    restrictReasonType = models.CharField(max_length=100, blank=True, null=True)
    submitterRep = models.CharField(max_length=100, blank=True, null=True)
    submitterRepAddress = models.CharField(max_length=255, blank=True, null=True)
    submitterRepCityState = models.CharField(max_length=100, blank=True, null=True)