# Generated by Django 5.0.4 on 2024-04-19 19:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dockets",
            name="agencyId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="dockets",
            name="docketType",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dockets",
            name="highlightedContent",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dockets",
            name="lastModifiedDate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="dockets",
            name="objectId",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="dockets",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="CFR",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="RIN",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="agencyId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="agencyType",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="dates",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="documentType",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="frDocNum",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="fullTextXmlUrl",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="furtherInformation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="lastModifiedDate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="objectId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="openForComment",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="postedDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="subAgy",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="subtype",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="summary",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="supplementaryInformation",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="documents",
            name="title",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="address1",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="address2",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="category",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="comment",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="commentOn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="country",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="email",
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="firstName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="govAgency",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="govAgencyType",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="lastName",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="modifyDate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="organization",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="originalDocumentId",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="pageCount",
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="phone",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="postedDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="reasonWithdrawn",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="receiveDate",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="restrictReason",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="restrictReasonType",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="stateProvinceRegion",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="submitterRep",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="submitterRepAddress",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="submitterRepCityState",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="subtype",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="title",
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="trackingNbr",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="zip",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
