# Generated by Django 5.0.4 on 2024-04-19 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "regulations",
            "0002_alter_dockets_agencyid_alter_dockets_dockettype_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="title",
            field=models.TextField(null=True),
        ),
    ]
