# Generated by Django 5.0.4 on 2024-04-19 21:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulations", "0003_alter_documents_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="documents",
            name="dates",
            field=models.TextField(null=True),
        ),
    ]
