# Generated by Django 4.2.11 on 2024-04-22 18:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulations", "0004_alter_documents_dates"),
    ]

    operations = [
        migrations.AlterField(
            model_name="publiccomments",
            name="postedDate",
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name="publiccomments",
            name="receiveDate",
            field=models.DateTimeField(null=True),
        ),
    ]
