# Generated by Django 5.0.4 on 2024-05-01 20:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "regulations",
            "0007_rename_publiccomments_comment_rename_dockets_docket_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="AgencyReference",
            fields=[
                (
                    "id",
                    models.CharField(max_length=10, primary_key=True, serialize=False),
                ),
                ("name", models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
