# Generated by Django 5.0.4 on 2024-05-06 19:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulations", "0009_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="NLPoutput",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("rep_comments", models.TextField(null=True)),
                (
                    "doc_plain_english_title",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("num_total_comments", models.IntegerField(default=0)),
                ("num_unique_comments", models.IntegerField(default=0)),
                ("num_representative_comment", models.IntegerField(default=0)),
                ("topics", models.TextField(null=True)),
                ("num_topics", models.IntegerField(default=0)),
                ("last_updated", models.DateTimeField(null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "document",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="regulations.document",
                    ),
                ),
            ],
        ),
    ]
