# Generated by Django 5.0.6 on 2024-05-18 17:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulations", "0010_nlpoutput_delete_search"),
    ]

    operations = [
        migrations.CreateModel(
            name="DataQA",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("added_at", models.DateTimeField(auto_now_add=True)),
                (
                    "data_id",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "data_type",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                ("error_message", models.TextField(null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="nlpoutput",
            name="rep_comments",
        ),
        migrations.AddField(
            model_name="nlpoutput",
            name="comments",
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name="nlpoutput",
            name="is_representative",
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name="docket",
            name="id",
            field=models.TextField(primary_key=True, serialize=False),
        ),
    ]
