# Generated by Django 5.0.6 on 2024-05-20 20:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulations", "0011_dataqa_remove_nlpoutput_rep_comments_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nlpoutput",
            name="comments",
            field=models.JSONField(null=True),
        ),
    ]
