# Generated by Django 5.0.6 on 2024-05-21 01:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("regulations", "0012_alter_nlpoutput_comments"),
    ]

    operations = [
        migrations.AlterField(
            model_name="nlpoutput",
            name="document",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="nlpoutput",
                to="regulations.document",
            ),
        ),
    ]
