name: CivicLens

on:
  push:
    branches: [ "main", "develop", "frontend", "backend", "devops" ]
  pull_request:
    branches: [ "main", "develop", "frontend", "backend"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    
    - uses: actions/setup-python@v5
      with:
        python-version: '3.10.12'

    - name: Install poetry
      run: |
        python -m pip install --upgrade pip
        pip install poetry==1.8.2

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: ~/.cache/pypoetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-
          
    - run: poetry install

    - name: lint with ruff
      run: poetry run ruff check --output-format=github .

    - name: run tests with pytest
      run: poetry run pytest

